"""Physics-Informed Neural Network core for thotbook-AmentI.

CPU-only PINN machinery used by 04_pinn_physics.ipynb to solve the Dirac,
Brans-Dicke and Wheeler-DeWitt equations.

**No PyTorch.** Automatic differentiation comes from `thotgrad` and the
optimisers from `thotopt`, both owned by this project and validated against
finite differences in `test_thotgrad.py`. The only third-party requirement is
NumPy, already a core dependency of `optimizr`.

SciPy appears in `pinn_problems.py` for *reference* solutions only. That is
deliberate: grading a solver against a solution produced by the same solver
would be circular, so the ground truth is generated by an independent,
battle-tested integrator.
"""
from __future__ import annotations

import time

import numpy as np

from thotgrad import MLP, Tensor          # noqa: F401  (MLP re-exported)
from thotopt import AdamW, lbfgs


def to_np(t) -> np.ndarray:
    """Tensor (or ndarray) -> flat ndarray."""
    data = t.data if isinstance(t, Tensor) else np.asarray(t)
    return np.asarray(data).reshape(-1)


def train_pinn(model: MLP, loss_fn, n_adam: int = 3000, n_lbfgs: int = 500,
               lr: float = 1e-3, log_every: int = 500, verbose: bool = True) -> dict:
    """Two-stage AdamW -> L-BFGS training, the canonical PINN recipe.

    AdamW escapes the poor initial basin cheaply; L-BFGS then exploits
    curvature to reach residuals no first-order method attains. `loss_fn` is a
    zero-argument closure returning a scalar `Tensor`.
    """
    hist: list[float] = []

    def value_and_grad(theta: np.ndarray):
        model.set_flat(theta)
        loss = loss_fn()
        loss.backward()
        return float(loss.data), model.grad_flat()

    theta = model.get_flat()

    t0 = time.time()
    opt = AdamW(lr=lr, weight_decay=0.0)
    for it in range(n_adam):
        f, g = value_and_grad(theta)
        theta = opt.step(theta, g)
        hist.append(f)
        if verbose and (it % log_every == 0 or it == n_adam - 1):
            print(f"  [AdamW] {it:5d}  loss = {f:.4e}")
    t_adam = time.time() - t0

    t1 = time.time()
    if n_lbfgs > 0:
        theta, f_final, n_it = lbfgs(value_and_grad, theta, max_iter=n_lbfgs,
                                     callback=hist.append)
        hist.append(f_final)
        if verbose:
            print(f"  [LBFGS] {n_it} iterations, final loss = {hist[-1]:.4e}")
    t_lbfgs = time.time() - t1

    model.set_flat(theta)
    return {"history": np.asarray(hist), "final_loss": hist[-1],
            "t_adam": t_adam, "t_lbfgs": t_lbfgs, "t_total": t_adam + t_lbfgs,
            "n_params": model.n_params()}


def l2_relative(pred: np.ndarray, exact: np.ndarray) -> float:
    """Relative L2 error ||pred-exact||_2 / ||exact||_2 — the standard PINN metric."""
    return float(np.linalg.norm(pred - exact) / (np.linalg.norm(exact) + 1e-300))
